[package]
name = "find-path"
version = "0.1.0"
edition = "2021"

[dependencies]
include_assets = "1.0.0"
lambda_http = "0.13.0"
nohash-hasher = "0.2.0"
priority-queue = "2.1.1"
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0.217"
serde_json = "1.0.134"

tokio = { version = "1", features = ["macros"] }
twox-hash = "2.1.0"
openssl = { version = "0.10.35", features = ["vendored"] }
